// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CSGL_Trade
{

    public partial class CSGOItems
    {
        public CSGOItems LoadNewInstance()
        {
            var sr = new System.IO.StreamReader(@"data\newschema.txt");
            using (sr)
            {
                var json = sr.ReadToEnd();
                var jObj = JObject.Parse(json);
                return JsonConvert.DeserializeObject<CSGOItems>(json);
            }
        }

        public class Weapon2
        {

            [JsonProperty("href")]
            public string Href { get; set; }

            [JsonProperty("text")]
            public string Text { get; set; }
        }
    }

    public partial class CSGOItems
    {
        public class Collection2
        {

            [JsonProperty("href")]
            public string Href { get; set; }

            [JsonProperty("text")]
            public string Text { get; set; }
        }
    }

    public partial class CSGOItems
    {
        public class Image2
        {

            [JsonProperty("href")]
            public string Href { get; set; }

            [JsonProperty("src")]
            public string Src { get; set; }

            [JsonProperty("text")]
            public string Text { get; set; }
        }
    }

    public partial class CSGOItems
    {
        public class Collection12
        {

            [JsonProperty("Weapon")]
            public Weapon2 Weapon { get; set; }

            [JsonProperty("Collection")]
            public Collection2 Collection { get; set; }

            [JsonProperty("Image")]
            public Image2 Image { get; set; }

            [JsonProperty("index")]
            public int Index { get; set; }

            [JsonProperty("url")]
            public string Url { get; set; }
        }
    }

    public partial class CSGOItems
    {
        public class Results2
        {

            [JsonProperty("collection1")]
            public Collection12[] Collection1 { get; set; }
        }
    }

    public partial class CSGOItems
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("frequency")]
        public string Frequency { get; set; }

        [JsonProperty("version")]
        public int Version { get; set; }

        [JsonProperty("newdata")]
        public bool Newdata { get; set; }

        [JsonProperty("lastrunstatus")]
        public string Lastrunstatus { get; set; }

        [JsonProperty("thisversionstatus")]
        public string Thisversionstatus { get; set; }

        [JsonProperty("nextrun")]
        public string Nextrun { get; set; }

        [JsonProperty("thisversionrun")]
        public string Thisversionrun { get; set; }

        [JsonProperty("results")]
        public Results2 Results { get; set; }
    }

}
